//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRT_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantIndicatorResultMeasurement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportantIndicatorResultMeasurement()
        {
            this.ForecastPeriod = new HashSet<ForecastPeriod>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IndicatorID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> PeriodMonthOrQuaterOrYearID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Isdelete { get; set; }
        public bool IsLastDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForecastPeriod> ForecastPeriod { get; set; }
        public virtual Indicator Indicator { get; set; }
        public virtual PeriodMonthOrQuaterOrYear PeriodMonthOrQuaterOrYear { get; set; }
    }
}
