//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRT_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MRTEntities : DbContext
    {
        public MRTEntities()
            : base("name=MRTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<ImportantIndicatorTargetMeasurement> ImportantIndicatorTargetMeasurements { get; set; }
        public virtual DbSet<Indicator> Indicators { get; set; }
        public virtual DbSet<IndicatorOwner> IndicatorOwners { get; set; }
        public virtual DbSet<IndicatorType> IndicatorTypes { get; set; }
        public virtual DbSet<IndicatorUnit> IndicatorUnits { get; set; }
        public virtual DbSet<IndicatorXIndicatorType> IndicatorXIndicatorTypes { get; set; }
        public virtual DbSet<SEOPlan> SEOPlans { get; set; }
        public virtual DbSet<Stategy> Stategies { get; set; }
        public virtual DbSet<StrategicObjective> StrategicObjectives { get; set; }
        public virtual DbSet<Tactic> Tactics { get; set; }
        public virtual DbSet<IndicatorDetailStatus> IndicatorDetailStatus { get; set; }
        public virtual DbSet<DataOwner> DataOwner { get; set; }
        public virtual DbSet<ForecastAnalysisResultsFile> ForecastAnalysisResultsFile { get; set; }
        public virtual DbSet<ForecastChangeActionPlanFile> ForecastChangeActionPlanFile { get; set; }
        public virtual DbSet<ForecastPeriod> ForecastPeriod { get; set; }
        public virtual DbSet<ForecastPeriodDocFile> ForecastPeriodDocFile { get; set; }
        public virtual DbSet<ForecastPeriodResultRemark> ForecastPeriodResultRemark { get; set; }
        public virtual DbSet<ForecastPeriodToolAndMethod> ForecastPeriodToolAndMethod { get; set; }
        public virtual DbSet<ForecastTool> ForecastTool { get; set; }
        public virtual DbSet<ForecastValueAndRealValue> ForecastValueAndRealValue { get; set; }
        public virtual DbSet<ImportantIndicatorResultMeasurement> ImportantIndicatorResultMeasurement { get; set; }
        public virtual DbSet<PeriodMonthOrQuaterOrYear> PeriodMonthOrQuaterOrYear { get; set; }
        public virtual DbSet<ForecastPeriodCompetitorValue> ForecastPeriodCompetitorValue { get; set; }
        public virtual DbSet<FilePath> FilePath { get; set; }
    }
}
